server:
  port: 80

myUploadPath: E:\fresh_upload

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/C76-S3-fresh
     username: root
     password: 123
     driver-class-name: com.mysql.jdbc.Driver
# 静态资源映射
  resources:
     staticLocations: 
        - classpath:/resources/
        - classpath:/static/
        - file:${myUploadPath}
        
  # 文件上传配置
  servlet:
     multipart:
        maxFileSize: 1000000000
  mail:
     # 邮箱服务器地址
     host: smtp.qq.com
     # 用户名
     username: 1511181137@qq.com
     # 密码 
     password: xazbkdnjctpkjgea
     # 字符集编码
     default-encoding: UTF-8   

# 以谁来发送邮件 自定义的参数
mail:
   fromMail:
      addr: 1511181137@qq.com
     
mybatis:
  #实体类的路径
  type-aliases-package: com.yc.fresh.bean
  configuration:
     map-underscore-to-camel-case: true    
     
     
# 日志配置
logging:
  level:
    com:
      yc:
        fresh:
          dao: debug
          web: warn      